indir: ../dataset/AnimatedDrawings/preprocessed
uid_json: ../dataset/AnimatedDrawings/drawings_uids.json

generator:
  kind: ffc_resnet
  input_nc: 4
  output_nc: 1
  ngf: 64
  n_downsampling: 3
  n_blocks: 9
  add_out_act: sigmoid
  init_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: false
  downsample_conv_kwargs:
    ratio_gin: ${generator.init_conv_kwargs.ratio_gout}
    ratio_gout: ${generator.downsample_conv_kwargs.ratio_gin}
    enable_lfu: false
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: ${generator.resnet_conv_kwargs.ratio_gin}
    enable_lfu: false

pretrained:
  # FFC-ResNet
  path: ./experiments/zhoujie_2024-05-12_02-43-10_train_lama-fourier.yaml_
  generator_checkpoint: epoch=3-step=3599_generator.ckpt

dataset:
  kind: default

device: cuda
